import type { Metadata } from "next";
import { Open_Sans, Source_Serif_4 } from "next/font/google";
import "./globals.css";
import { twJoin } from "tailwind-merge";
import { AppWrapper } from "./components/AppWrapper/AppWrapper";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

const sourceSerif = Source_Serif_4({
  variable: "--font-source-serif",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="h-full" lang="en">
      <body
        className={twJoin(
          "h-full antialiased",
          openSans.variable,
          sourceSerif.variable,
        )}
      >
        <AppWrapper>{children}</AppWrapper>
      </body>
    </html>
  );
}
